schema_version = "1.0.0"
id = "hw_parts_based_animation"
version = "0.1.0"
name = "HW Parts-based Animation"
tagline = "Utilities for Horizon Worlds parts-based character workflows"
maintainer = "Todd Roberts"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]